[ci]
runtime = "nix"
runner = "codefloe-global"
workspace = true
with_msrv = true
step_runners = { cargo-clippy = "codeberg-small", cargo-doc = "codeberg-small", cargo-fmt = "codeberg-tiny", cargo-package = "codeberg-medium", cargo-test = "codeberg-medium", nix-check = "atlas-nix-trusted", quality-tools = "codeberg-small" }
provider = "crow"
platform = "forgejo"
publish_crates = true

[ci.pages]
repo = "caniko/tzu"
canonical_domain = "tzu.tartanoglu.com"
source_branch = "main"
